title: Orion SDK
description: SolarWinds Orion SDK Documentation
github_repo: https://github.com/solarwinds/OrionSDK
theme: jekyll-theme-minimal
baseurl: "/OrionSDK"

plugins:
  - jemoji

# Build settings
markdown: kramdown
permalink: pretty

# Include docs folder
include:
  - docs

# Exclude version folders from Jekyll processing
exclude:
  - LICENSE

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: default
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
