//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwqlStudio.XmlRender {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlRender {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlRender() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwqlStudio.XmlRender.XmlRender", typeof(XmlRender).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;!-- borrowed from http://forums.devx.com/archive/index.php/t-4702.html --&gt;
        ///&lt;!-- According to the above URL, this code belongs to Microsoft --&gt;
        ///&lt;!-- Thanks Microsoft. :) Cool XSL. --&gt;
        ///&lt;x:stylesheet xmlns:x=&quot;http://www.w3.org/TR/WD-xsl&quot;
        ///xmlns:dt=&quot;urn:schemas-microsoft-com:datatypes&quot;
        ///xmlns:d2=&quot;uuid:C2F41010-65B3-11d1-A29F-00AA00C14882&quot;&gt;
        ///  &lt;x:template match=&quot;/&quot; xml:space=&quot;default&quot;&gt;
        ///    &lt;HTML&gt;
        ///      &lt;HEAD&gt;
        ///        &lt;STYLE&gt;
        ///          BODY{font:x-small &apos;Verdana&apos;;margin-right:1.5em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLToHTML {
            get {
                return ResourceManager.GetString("XMLToHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--
        /// |
        /// | XSLT REC Compliant Version of IE5 Default Stylesheet
        /// |
        /// | Original version by Jonathan Marsh (jmarsh@xxxxxxxxxxxxx)
        /// | http://msdn.microsoft.com/xml/samples/defaultss/defaultss.xsl
        /// |
        /// | Conversion to XSLT 1.0 REC Syntax by Steve Muench (smuench@xxxxxxxxxx)
        /// | 
        /// | Further conversion by George Zabanah as follows:
        /// |
        /// | 24-Mar-2008 George Zabanah Fix to cdata function. 
        /// |                            Was supposed to check cdata != null.
        /// |       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlToHtml10 {
            get {
                return ResourceManager.GetString("XmlToHtml10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--
        /// |
        /// | XSLT REC Compliant Version of IE5 Default Stylesheet
        /// |
        /// | Original version by Jonathan Marsh (jmarsh@xxxxxxxxxxxxx)
        /// | http://msdn.microsoft.com/xml/samples/defaultss/defaultss.xsl
        /// |
        /// | Conversion to XSLT 1.0 REC Syntax by Steve Muench (smuench@xxxxxxxxxx)
        /// |
        /// | 14-Mar-2008 George Zabanah Modifications made to the XSLT stylesheet
        /// |                            to add a little spacing and change default colour
        /// |                            of na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlToHtml10Basic {
            get {
                return ResourceManager.GetString("XmlToHtml10Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--
        /// |
        /// | XSLT REC Compliant Version of IE5 Default Stylesheet
        /// |
        /// | Original version by Jonathan Marsh (jmarsh@xxxxxxxxxxxxx)
        /// | http://msdn.microsoft.com/xml/samples/defaultss/defaultss.xsl
        /// |
        /// | Conversion to XSLT 1.0 REC Syntax by Steve Muench (smuench@xxxxxxxxxx)
        /// | 
        /// | Further conversion by George Zabanah as follows:
        /// |
        /// | 24-Mar-2008 George Zabanah RegExp Only-Version
        /// | 14-Mar-2008 George Zabanah Modifications made to the XSLT stylesheet
        /// |      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlToHtml10Cdata {
            get {
                return ResourceManager.GetString("XmlToHtml10Cdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--
        /// |
        /// | XSLT REC Compliant Version of IE5 Default Stylesheet
        /// |
        /// | Original version by Jonathan Marsh (jmarsh@xxxxxxxxxxxxx)
        /// | http://msdn.microsoft.com/xml/samples/defaultss/defaultss.xsl
        /// |
        /// | Conversion to XSLT 1.0 REC Syntax by Steve Muench (smuench@xxxxxxxxxx)
        /// | 
        /// | Further conversion by George Zabanah as follows:
        /// |
        /// | 24-Mar-2008 George Zabanah RegExp Only-Version
        /// | 14-Mar-2008 George Zabanah Modifications made to the XSLT stylesheet
        /// |      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlToHtml10Plus {
            get {
                return ResourceManager.GetString("XmlToHtml10Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!--
        /// |
        /// | XSLT REC Compliant Version of IE5 Default Stylesheet
        /// |
        /// | Original version by Jonathan Marsh (jmarsh@xxxxxxxxxxxxx)
        /// | http://msdn.microsoft.com/xml/samples/defaultss/defaultss.xsl
        /// |
        /// | Conversion to XSLT 1.0 REC Syntax by Steve Muench (smuench@xxxxxxxxxx)
        /// | 
        /// | Further conversion by George Zabanah as follows:
        /// |
        /// | 04-Apr-2008 George Zabanah Converted to XSLT 2.0 Stylesheet for use with Saxon
        /// |                            Added XML declarat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XSLTHtml20 {
            get {
                return ResourceManager.GetString("XSLTHtml20", resourceCulture);
            }
        }
    }
}
