//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwqlStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int OperationTimeout {
            get {
                return ((int)(this["OperationTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17777")]
        public int DefaultInfoServicePort {
            get {
                return ((int)(this["DefaultInfoServicePort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Orion/ssl")]
        public string OrionEndpointPath {
            get {
                return ((string)(this["OrionEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/EOC")]
        public string EOCEndpointPath {
            get {
                return ((string)(this["EOCEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SW/InformationService/IPAM")]
        public string IPAMEndpointPath {
            get {
                return ((string)(this["IPAMEndpointPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousServers {
            get {
                return ((string)(this["PreviousServers"]));
            }
            set {
                this["PreviousServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousUsers {
            get {
                return ((string)(this["PreviousUsers"]));
            }
            set {
                this["PreviousUsers"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Cirrus/ssl")]
        public string NCMEndpointPath {
            get {
                return ((string)(this["NCMEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/OrionBasic")]
        public string OrionHttpsEndpointPath {
            get {
                return ((string)(this["OrionHttpsEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17778")]
        public int DefaultInfoServiceHttpsPort {
            get {
                return ((int)(this["DefaultInfoServiceHttpsPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/NCMIntegration/ssl")]
        public string NCMForwarderEndpointPath {
            get {
                return ((string)(this["NCMForwarderEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Cirrus")]
        public string NCMWindowsEndpointPath {
            get {
                return ((string)(this["NCMWindowsEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Orion/ssl/compressed")]
        public string OrionEndpointPathCompressed {
            get {
                return ((string)(this["OrionEndpointPathCompressed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Orion/ad")]
        public string OrionEndpointPathAD {
            get {
                return ((string)(this["OrionEndpointPathAD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Orion/ad/compressed")]
        public string OrionEndpointPathADCompressed {
            get {
                return ((string)(this["OrionEndpointPathADCompressed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCompressedModes {
            get {
                return ((bool)(this["ShowCompressedModes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/Orion/certificate")]
        public string OrionEndpointPathCertificate {
            get {
                return ((string)(this["OrionEndpointPathCertificate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousServerType {
            get {
                return ((string)(this["PreviousServerType"]));
            }
            set {
                this["PreviousServerType"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds-Orion")]
        public string CertificateSubjectName {
            get {
                return ((string)(this["CertificateSubjectName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/v3/Orion/ssl")]
        public string OrionV3EndpointPath {
            get {
                return ((string)(this["OrionV3EndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/v3/OrionBasic")]
        public string OrionV3HttpsEndpointPath {
            get {
                return ((string)(this["OrionV3HttpsEndpointPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/v3/Orion/ad")]
        public string OrionV3EndpointPathAD {
            get {
                return ((string)(this["OrionV3EndpointPathAD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/v3/Orion/ad/compressed")]
        public string OrionV3EndpointPathADCompressed {
            get {
                return ((string)(this["OrionV3EndpointPathADCompressed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/v3/Orion/ssl/compressed")]
        public string OrionV3EndpointPathCompressed {
            get {
                return ((string)(this["OrionV3EndpointPathCompressed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SolarWinds/InformationService/v3/Orion/certificate")]
        public string OrionV3EndpointPathCertificate {
            get {
                return ((string)(this["OrionV3EndpointPathCertificate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("services/InformationService")]
        public string JavaEndpointPath {
            get {
                return ((string)(this["JavaEndpointPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateRequired {
            get {
                return ((bool)(this["UpdateRequired"]));
            }
            set {
                this["UpdateRequired"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8443")]
        public int DefaultJavaInfoServicePort {
            get {
                return ((int)(this["DefaultJavaInfoServicePort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseActiveSubscriber {
            get {
                return ((bool)(this["UseActiveSubscriber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ByNamespace")]
        public string EntityGroupingMode {
            get {
                return ((string)(this["EntityGroupingMode"]));
            }
            set {
                this["EntityGroupingMode"] = value;
            }
        }
    }
}
